export const GET_CHARACTER_LIST = 'GET_CHARACTER_LIST';
export const GET_CHARACTER_LIST_SUCCESS = 'GET_CHARACTER_LIST_SUCCESS';
export const GET_CHARACTER_LIST_FAILED = 'GET_CHARACTER_LIST_FAILED';

export const ADD_CHARACTER = 'ADD_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const FILTER_CHARACTER_LIST = 'FILTER_CHARACTER_LIST';